### ISSUE TITLE
made alternative version of this

### ISSUE THREAD

**Issue by hopdebee** [strizhechenko/bandcamp-player#4]
Hey, 

Just letting you know I used this code as a starting point to make https://github.com/hopdebee/bandcamp-player-evo. 

Its now slightly less elegant since it uses a js library to scrape bandcamp, but it works. Let me know if you have issues in the issues section there.

**Comment by strizhechenko** [comment]
Nah, I'm happy this code and idea living its' best live and somebody helps them :)
